title: MinJae
description: Welcome My Blog!

url: https://aldrn3333.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  

social:
  github: aldrn3333
  email: alswo3333@kookmin.ac.kr
  

google_analytics: "UA-58263416-1"

comment:
  provider: "disqus"
  disqus:
    shortname: "Ming"
